# Config file for automatic testing at travis-ci.org

sudo: false
language: python

python:
  - "2.7"
  - "2.6"

notifications:
  email:
    on_success: always

install: pip install -r dev-requirements.txt  --use-mirrors

# command to run tests, e.g. python setup.py test
script:
  - manage lint
  - manage test

after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "true" ]]; then exit 0; fi
  - if [[ "$TRAVIS_BRANCH" != "master" ]]; then exit 0; fi
  - manage release
